### ISSUE TITLE
Error in first run

### ISSUE THREAD

**Issue by Shakhboz95** [nateshmbhat/card-scanner-flutter#19]
App crashes in first run during scan the card. 
After this it works.
Here is the error log:

`
java.lang.ExceptionInInitializerError
E/AndroidRuntime(12092): 	at androidx.camera.core.Preview.<clinit>(Preview.java:143)
E/AndroidRuntime(12092): 	at androidx.camera.core.Preview$Builder.build(Preview.java:678)
E/AndroidRuntime(12092): 	at com.nateshmbhat.card_scanner.CardScannerCameraActivity.bindPreviewUseCase(CardScannerCameraActivity.kt:100)
E/AndroidRuntime(12092): 	at com.nateshmbhat.card_scanner.CardScannerCameraActivity.bindAllCameraUseCases(CardScannerCameraActivity.kt:92)
E/AndroidRuntime(12092): 	at com.nateshmbhat.card_scanner.CardScannerCameraActivity.onResume(CardScannerCameraActivity.kt:139)
E/AndroidRuntime(12092): 	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1413)
E/AndroidRuntime(12092): 	at android.app.Activity.performResume(Activity.java:7400)
E/AndroidRuntime(12092): 	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3820)
E/AndroidRuntime(12092): 	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3860)
E/AndroidRuntime(12092): 	at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:51)
E/AndroidRuntime(12092): 	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:145)
E/AndroidRuntime(12092): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
E/AndroidRuntime(12092): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1831)
E/AndroidRuntime(12092): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(12092): 	at android.os.Looper.loop(Looper.java:201)
E/AndroidRuntime(12092): 	at android.app.ActivityThread.main(ActivityThread.java:6810)
E/AndroidRuntime(12092): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(12092): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
E/AndroidRuntime(12092): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
E/AndroidRuntime(12092): Caused by: java.lang.IllegalStateException: java.util.concurrent.ExecutionException: java.lang.IllegalStateException: Must call CameraX.initialize() first
E/AndroidRuntime(12092): 	at androidx.camera.core.CameraX.waitInitialized(CameraX.java:933)
E/AndroidRuntime(12092): 	at androidx.camera.core.CameraX.checkInitialized(CameraX.java:814)
E/AndroidRuntime(12092): 	at androidx.camera.core.CameraX.getSurfaceManager(CameraX.java:581)
E/AndroidRuntime(12092): 	at androidx.camera.core.Preview$Defaults.<clinit>(Preview.java:570)
E/AndroidRuntime(12092): 	... 19 more
E/AndroidRuntime(12092): Caused by: java.util.concurrent.ExecutionException: java.lang.IllegalStateException: Must call CameraX.initialize() first
E/AndroidRuntime(12092): 	at androidx.camera.core.impl.utils.futures.ImmediateFuture$ImmediateFailedFuture.get(ImmediateFuture.java:135)
E/AndroidRuntime(12092): 	at androidx.camera.core.impl.utils.futures.ImmediateFuture.get(ImmediateFuture.java:94)
E/AndroidRuntime(12092): 	at androidx.camera.core.CameraX.waitInitialized(CameraX.java:931)
E/AndroidRuntime(12092): 	... 22 more
E/AndroidRuntime(12092): Caused by: java.lang.IllegalStateException: Must call CameraX.initialize() first
E/AndroidRuntime(12092): 	at androidx.camera.core.CameraX.getInstanceLocked(CameraX.java:914)
E/AndroidRuntime(12092): 	at androidx.camera.core.CameraX.getInstance(CameraX.java:905)
E/AndroidRuntime(12092): 	at androidx.camera.core.CameraX.waitInitialized(CameraX.java:929)
E/AndroidRuntime(12092): 	... 22 more
`

**Comment by nateshmbhat** [comment]
fixed
