### ISSUE TITLE
cardDetails returns nothing

### ISSUE THREAD

**Issue by cru1se** [nateshmbhat/card-scanner-flutter#20]
code:
var cardDetails = await CardScanner.scanCard();
print(cardDetails);

Staying in the scanner, no cardDetails returned

**Comment by nateshmbhat** [comment]
it will return card details only if it was able to detect a valid credit/debit card.

**Comment by TheArchitect123** [comment]
Hi there,

This is a great package. However I've tried running this on Android. Both with a real card, and a virtual card (Image), and it still returns null. 

When I run the logs, I get results such as the CardNumber, CardType, all outputted to the console window, but no results are returned from the method channel
