### ISSUE TITLE
Staying in the scanner, no valid cardDetails

### ISSUE THREAD

**Issue by flenair** [nateshmbhat/card-scanner-flutter#25]
code:
var cardDetails = await CardScanner.scanCard();
print(cardDetails);

Staying in the scanner, no cardDetails returned

Tried with real french credit card, tried also with picture of american credit card on internet .

Can u tell me what is a valid credit card ?

Thanks

**Comment by MateusHBR** [comment]
here is the same issue...

**Comment by nateshmbhat** [comment]
valid card is right now 15 to 16 digits which passes "Luhn algorithm"

**Comment by nateshmbhat** [comment]
anyway Card scanner is getting a big overhaul with much better accuracy and configuration options. stay tuned.

**Comment by amelmusic** [comment]
Are you using different models for embossed credit card? Google's ML model is not good with embossed font and will almost always confuse 7 with 1.

**Comment by amelmusic** [comment]
Just tried. Doesn't work with CC's that has embossed font :(

**Comment by nateshmbhat** [comment]
have added a timeout option in the widget to address this issue. 
Security of scanning has been improved, try check the latest version which gives options on screen to tweak parameters at run time in the example app itself.
