### ISSUE TITLE
F-Droid inclusion

### ISSUE THREAD

**Issue by IzzySoft** [nateshmbhat/card-scanner-flutter#28]
You've opened [a merge request](https://gitlab.com/fdroid/fdroiddata/-/merge_requests/7127) to have your app included with F-Droid, marked it "WIP" – and disappeared. Are you still pursuing that? You're not answering questions there (most likely the notifications got lost), which is why I'm bringing this up here. If there's no response, we'll simply close that MR as it cannot be processed and seems stale.

Should you still be interested, and need help, you just need to ask.

**Comment by nateshmbhat** [comment]
hey please close the merge request. i'm not working on it currently.

**Comment by IzzySoft** [comment]
Will do, thanks for the fast reply! Should you pick up again, we can "start over" anytime. Best luck with your current projects then!
