### ISSUE TITLE
What are the supported scanning devices

### ISSUE THREAD

**Issue by shubie** [nateshmbhat/card-scanner-flutter#3]
Hello,

Not an issue. Just inquisitive of the supported scanning devices this plugin supports? 

Does it use a Camera? Or it can read any card reader?

**Comment by nateshmbhat** [comment]
It uses the device camera

**Comment by shubie** [comment]
Okay. Thanks.
Do you know of anyone that can read from scanners?

**Comment by nateshmbhat** [comment]
Nope 😕.
