### ISSUE TITLE
How can I fix this?? 

### ISSUE THREAD

**Issue by leegiseong20030603** [nateshmbhat/card-scanner-flutter#31]
I am using Android language setting in Java. We are currently experiencing these problems with the card scanner Flutter package. How can I fix this??

`e: /Users/leegiseong/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/card_scanner-0.2.0+3/android/src/main/java/com/nateshmbhat/card_scanner/CardScannerCameraActivity.kt: (47, 23): Type mismatch: inferred type is CardScanOptions? but CardScanOptions was expected
e: /Users/leegiseong/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/card_scanner-0.2.0+3/android/src/main/java/com/nateshmbhat/card_scanner/scanner_core/models/CardDetails.kt: (15, 11): Type mismatch: inferred type is String? but String was expected
e: /Users/leegiseong/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/card_scanner-0.2.0+3/android/src/main/java/com/nateshmbhat/card_scanner/scanner_core/models/CardDetails.kt: (16, 11): Type mismatch: inferred type is String? but String was expected
e: /Users/leegiseong/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/card_scanner-0.2.0+3/android/src/main/java/com/nateshmbhat/card_scanner/scanner_core/models/CardDetails.kt: (17, 11): Type mismatch: inferred type is String? but String was expected
e: /Users/leegiseong/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/card_scanner-0.2.0+3/android/src/main/java/com/nateshmbhat/card_scanner/scanner_core/models/CardDetails.kt: (18, 11): Type mismatch: inferred type is String? but String was expected`

**Comment by akyazilim61** [comment]
any soluion please...  @leegiseong20030603  @m-zaink

**Comment by nateshmbhat** [comment]
fixed in current version
