### ISSUE TITLE
Error when I build for iOS with the new version

### ISSUE THREAD

**Issue by jpgSouza** [nateshmbhat/card-scanner-flutter#44]
I'm getting the following error when a try to build for iOS.

Command CompileSwift failed with a nonzero exit code
    <unknown>:0: error: filename "CameraViewController.swift" used twice: '/Users/jpgsouza/Documents/cec_flutter/lib/packages/card-scanner-flutter-0.2.1/ios/Classes/CameraViewController.swift' and '/Users/jpgsouza/Documents/cec_flutter/lib/packages/card-scanner-flutter-0.2.1/ios/Classes/Scanner Core/CameraViewController.swift'
    <unknown>:0: note: filenames are used to distinguish private declarations with the same name
    <unknown>:0: error: filename "ScanProcessor.swift" used twice: '/Users/jpgsouza/Documents/cec_flutter/lib/packages/card-scanner-flutter-0.2.1/ios/Classes/ScanProcessor.swift' and '/Users/jpgsouza/Documents/cec_flutter/lib/packages/card-scanner-flutter-0.2.1/ios/Classes/Scanner Core/ScanProcessor.swift'
    <unknown>:0: note: filenames are used to distinguish private declarations with the same name

**Comment by AzarouAmine** [comment]
Facing same issue.

**Comment by nateshmbhat** [comment]
The fixes have been published in 1.0.1-prerelease version

**Comment by jpgSouza** [comment]
Thx. Its works
