### ISSUE TITLE
Cannot find symbol method registerWith on CardScannerPlugin

### ISSUE THREAD

**Issue by PatrickSLuz** [nateshmbhat/card-scanner-flutter#5]
Flutter Version: 1.17.5
Fail to open app.
Error:
`...\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java:35: error: cannot find symbol
    CardScannerPlugin.registerWith(registry.registrarFor("com.nateshmbhat.card_scanner.CardScannerPlugin"));
                                   
  symbol:   method registerWith(Registrar)
  location: class CardScannerPlugin
1 error

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 16s
Exception: Gradle task assembleDebug failed with exit code 1
Exited (sigterm)`

**Comment by nateshmbhat** [comment]
can you check the latest version (v0.1.0)  ?

**Comment by PatrickSLuz** [comment]
Now it worked, thanks!

**Comment by timothychristensen** [comment]
Installed card_scanner 0.1.0+1 today. Able to get it to build and run on iOS. Building to my Android device to test, I get the same error. I have tried everything I can think of and cannot solve this issue. When I open the project as an Android projects, I can get to those resources from within the editor, so this doesn't make any sense to me. Any ideas?

/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java:43: error: cannot find symbol
    CardScannerPlugin.registerWith(registry.registrarFor("com.nateshmbhat.card_scanner.CardScannerPlugin"));
                     ^
  symbol:   method registerWith(Registrar)
  location: class CardScannerPlugin
1 error

/SDK/flutter/bin/flutter doctor --verbose
[✓] Flutter (Channel stable, v1.17.5, on Mac OS X 10.15.5 19F101, locale en-US)
    • Flutter version 1.17.5 at /Users/tim/Projects/SDK/flutter
    • Framework revision 8af6b2f038 (3 weeks ago), 2020-06-30 12:53:55 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Library/Android/sdk
    • Platform android-29, build-tools 28.0.3
    • ANDROID_HOME = /Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.1

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[!] VS Code (version 1.38.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (3 available)
    • Nokia 6 1                  • PL2GARH861100445                         • android-arm64 • Android 10 (API 29)
    • iPhone               • 4c37a12bae6b361b693a4701c173ed90662c954b • ios           • iOS 13.3
    • iPhone SE (2nd generation) • FFD447F3-5965-4D2E-8BC6-8B1868722A74     • ios           • com.apple.CoreSimulator.SimRuntime.iOS-13-5 (simulator)

**Comment by nateshmbhat** [comment]
Can u try again by upgrading flutter to 1.19 ?

**Comment by timothychristensen** [comment]
Hi,

I get the exact same error after upgrading to 1.20.1.

[✓] Flutter (Channel stable, 1.20.1, on Mac OS X 10.15.6 19G73, locale en-US)
    • Flutter version 1.20.1 at /SDK/flutter
    • Framework revision 2ae34518b8 (8 days ago), 2020-08-05 19:53:19 -0700
    • Engine revision c8e3b94853
    • Dart version 2.9.0

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Library/Android/sdk
    • Platform android-29, build-tools 28.0.3
    • ANDROID_HOME = /Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.1

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 48.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[!] VS Code (version 1.47.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (3 available)

**Comment by scrlkx** [comment]
Hi,

I'm having the same issue. Someone have a workaround or must we reopen this?
