### ISSUE TITLE
Missing backward compatibility with pre 1.12 Android projects

### ISSUE THREAD

**Issue by NicolaeC** [nateshmbhat/card-scanner-flutter#8]
Hi, could you please add `registerWith` method for `CardScannerPlugin`?

As mentioned [https://github.com/flutter/flutter/wiki/Upgrading-pre-1.12-Android-projects](here), plugins developed exclusively on the new plugins API will not work on older pre-1.12 Android projects.

**Comment by nateshmbhat** [comment]
the old way of registering plugins is deprecated now.
