### ISSUE TITLE
unable to build on android with firebase

### ISSUE THREAD

**Issue by savy-91** [nateshmbhat/card-scanner-flutter#9]
Hi, I wanted to try this in an app  that uses various firebase plugins.

When building i get the following error:

```
java.lang.RuntimeException: java.lang.RuntimeException: Duplicate class com.google.firebase.components.AbstractComponentContainer found in modules firebase-common-19.2.0-runtime.jar (com.google.firebase:firebase-common:19.2.0) and jetified-firebase-components-16.0.0-runtime.jar (com.google.firebase:firebase-components:16.0.0)
...
```
The error happens only when I add card_scanner as a dependency and goes away as soon as I remove it. I tried creating a new project and it happens also in the new project with the following dependencies:

```
  firebase_auth_ui: ^1.0.1
  firebase_auth: ^0.14.0+5
  firebase_crashlytics: ^0.1.3+3
  firebase_messaging: ^6.0.16
  firebase_analytics: ^5.0.16
  card_scanner: ^0.1.0+1
```

**Comment by thomaaam** [comment]
I am using the exact same packages except for `firebase_auth_ui` and the fact that I use `firebase_auth: ^0.16.1` over `firebase_auth: ^0.14.0+5`. Version `0.1.0+1` builds fine for me on Android.

It doesn't really help the issue, but I thought you should know.

**Comment by savy-91** [comment]
It actually helps, I removed firebase_auth_ui and as you said it works. I will close this as the issue I was having was caused by using an outdated dependency for another package. Thanks for the tip @thomaaam !
